---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-openwhisk
  namespace: openwhisk
  labels:
    name: configure-openwhisk
spec:
  completions: 1
  template:
    metadata:
      labels:
        name: config
    spec:
      restartPolicy: Never
      containers:
      - name: configure-openwhisk
        image: danlavine/whisk_config:dev
        imagePullPolicy: Always
        command: [ "/openwhisk-devtools/kubernetes/configure/configure.sh" ]
